version: '3.6'

services:

  www:
    image: node:lts-buster
    volumes:
      - './www:/app'
    working_dir: '/app'
    entrypoint: '/bin/bash -c'
    user: node
    command:
      - |
        npm start -- -H 0.0.0.0
    networks: [ 'my-network' ]
    ports: [ '8000:8000' ]

networks:
  my-network:
