version: '3.7'

services:

  www:
    image: node
    volumes:
      - './www:/app'
    working_dir: '/app'
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm start
    networks: [ 'my-network' ]
    ports: [ '8000:8000' ]
networks:
  my-network:
