version: '3.6'

services:

  www:
    image: node:lts-buster
    volumes:
      - './www:/app'
    working_dir: '/app'
    entrypoint: '/bin/bash -c'
    user: node
    command:
      - |
        npm start -- -H 0.0.0.0
    ports: [ '8000:8000' ]

  next-blog:
    image: node
    volumes:
      - './next-blog:/app'
    working_dir: '/app'
    entrypoint: '/bin/bash -c'
    user: node
    command:
      - |
        npm run dev
        tail -f /dev/null
        npm start -- -H 0.0.0.0
    ports: [ '3000:3000' ]
